version: '3'

x-hostname: &hostname
  "clientlibapp"
services:  
  # add external api service
  tests-container:
    image: golang:latest
    environment:
      API_HOSTNAME: *hostname
    depends_on: 
      - accountapi
    volumes:
      - ./:/src
    entrypoint: ["/bin/bash", "-c"]
    command: ["sleep 3 && cd /src/library/helpers && go test -v --cover && cd /src/library/account && go test -v --cover"] 

  postgresql:
    image: postgres:9.5-alpine
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d/

  vault:
    image: vault:1.6.3
    environment:
      - SKIP_SETCAP=1
      - VAULT_DEV_ROOT_TOKEN_ID=8fb95528-57c6-422e-9722-d2147bcba8ed
